CREATE TABLE IF NOT EXISTS core_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no VARCHAR(64) NOT NULL UNIQUE,
    account_seq_no BIGINT UNIQUE,
    customer_no VARCHAR(64),
    account_type VARCHAR(32) NOT NULL,
    subject_code VARCHAR(64),
    normal_balance_direction VARCHAR(8),
    owner_id VARCHAR(64) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    available_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
    frozen_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
    interest_rate DECIMAL(12, 8),
    last_accrual_date DATE,
    status VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS core_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    core_txn_id VARCHAR(64) NOT NULL UNIQUE,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    biz_order_id VARCHAR(64) NOT NULL,
    biz_type VARCHAR(64) NOT NULL,
    txn_type VARCHAR(64) NOT NULL,
    customer_no VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    debit_account_no VARCHAR(64) NOT NULL,
    debit_account_seq_no BIGINT NOT NULL,
    debit_subject_code VARCHAR(64) NOT NULL,
    credit_account_no VARCHAR(64) NOT NULL,
    credit_account_seq_no BIGINT NOT NULL,
    credit_subject_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(64),
    failure_message VARCHAR(255),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS core_ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    core_txn_id VARCHAR(64) NOT NULL,
    entry_no INT NOT NULL,
    account_no VARCHAR(64) NOT NULL,
    account_seq_no BIGINT,
    customer_no VARCHAR(64),
    subject_code VARCHAR(64) NOT NULL,
    entry_direction VARCHAR(32) NOT NULL,
    dc_direction VARCHAR(8) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    balance_before DECIMAL(18, 2) NOT NULL,
    balance_after DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_core_ledger_entry_txn_entry UNIQUE (core_txn_id, entry_no)
);

CREATE TABLE IF NOT EXISTS core_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(64) NOT NULL,
    entity_id VARCHAR(64) NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    operator_id VARCHAR(64),
    trace_id VARCHAR(64),
    before_snapshot CLOB,
    after_snapshot CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS core_transaction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    core_txn_id VARCHAR(64) NOT NULL,
    before_status VARCHAR(32),
    after_status VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    message VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);
